services:
  watchtower:
    image: containrrr/watchtower
    command:
      - "--label-enable"
      - "--interval"
      - "30"
      - "--rolling-restart"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
  reverse-proxy:
    image: traefik:v3.1
    command:
      - "--providers.docker"
      - "--providers.docker.exposedbydefault=false"
      - "--entryPoints.websecure.address=:443"
      - "--entryPoints.websecure.http.tls.options=default"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=adminuser@redful.xyz"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - letsencrypt:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
  red-app:
    image: ghcr.io/redcloud442/red:prod
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.red-app.rule=Host(`redful.xyz`)"
      - "traefik.http.routers.red-app.entrypoints=websecure"
      - "traefik.http.routers.red-app.tls.certresolver=myresolver"
      - "com.centurylinklabs.watchtower.enable=true"
    volumes:
      - ./secrets:/run/secrets:ro
    environment:
      - DATABASE_URL=/run/secrets/databaseUrl.txt
      - DIRECT_URL=/run/secrets/directUrl.txt
      - NEXT_PUBLIC_SUPABASE_URL=/run/secrets/supabaseUrl.txt
      - NEXT_PUBLIC_SUPABASE_ANON_KEY=/run/secrets/anon.txt
      - NEXT_PUBLIC_BASE_URL=https://redful.xyz
      - NEXT_PUBLIC_CRYPTO_SECRET_KEY=/run/secrets/cryptokey.txt
      - SUPABASE_SERVICE_ROLE_KEY=/run/secrets/role.txt
    deploy:
      mode: replicated
      replicas: 3
    restart: always
volumes:
  letsencrypt:
