version: "3.8"

services:
  watchtower:
    image: containrrr/watchtower
    command:
      - "--label-enable"
      - "--interval"
      - "30"
      - "--rolling-restart"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  reverse-proxy:
    image: traefik:v3.1
    command:
      - "--providers.docker"
      - "--providers.docker.exposedbydefault=false"
      - "--entryPoints.websecure.address=:443"
      - "--providers.docker"
      - "--providers.docker.exposedbydefault=false"
      - "--entryPoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=adminuser@greenful.website"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - letsencrypt:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always

  red-app:
    image: ghcr.io/redcloud442/red:prod
    secrets:
      - red_app_env
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.red-app.loadbalancer.server.port=8080"
      - "traefik.http.routers.red-app.rule=Host(`greenful.website`)"
      - "traefik.http.routers.red-app.entrypoints=websecure"
      - "traefik.http.routers.red-app.tls.certresolver=myresolver"
    build:
      context: .
      dockerfile: Dockerfile
    deploy:
      mode: replicated
      replicas: 3
      restart_policy:
        condition: on-failure
    restart: always

volumes:
  letsencrypt:

secrets:
  red_app_env:
    file: /etc/secrets/.env
