version: "3.8"
services:
  web:
    image: ghcr.io/redcloud442/red:prod
    environment:
      NEXT_PUBLIC_SUPABASE_URL: /run/secrets/supabaseUrl
      NEXT_PUBLIC_SUPABASE_ANON_KEY: /run/secrets/anonKey
      NEXT_PUBLIC_BASE_URL: /run/secrets/baseUrl
      NEXT_PUBLIC_CRYPTO_SECRET_KEY: /run/secrets/cryptokey
      SUPABASE_SERVICE_ROLE_KEY: /run/secrets/serviceRoleKey
      DATABASE_URL: /run/secrets/databaseUrl
      DIRECT_URL: /run/secrets/directUrl
    secrets:
      - databaseUrl
      - directUrl
      - supabaseUrl
      - anonKey
      - cryptokey
      - serviceRoleKey
      - baseUrl
    deploy:
      mode: replicated
      replicas: 3
      update_config:
        order: start-first
    ports:
      - "8080:8080"

  cloudflared:
    image: cloudflare/cloudflared:latest
    command: tunnel --no-autoupdate run
    networks:
      - public
    secrets:
      - tunnelKey
    environment:
      - TUNNEL_TOKEN=/run/secrets/tunnelKey
    deploy:
      replicas: 1

secrets:
  databaseUrl:
    external: true
  directUrl:
    external: true
  supabaseUrl:
    external: true
  anonKey:
    external: true
  cryptokey:
    external: true
  serviceRoleKey:
    external: true
  baseUrl:
    external: true
  tunnelKey:
    external: true

networks:
  public:
    external: true
