version: "3.8"
services:
  web:
    image: ghcr.io/redcloud442/mithril:prod
    deploy:
      mode: replicated
      replicas: 3
      update_config:
        order: start-first
    ports:
      - "8080:8080"
  server:
    image: ghcr.io/redcloud442/mithril:prod-server
    deploy:
      mode: replicated
      replicas: 3
      update_config:
        order: start-first
    ports:
      - "3000:3000"
  cloudflared:
    image: cloudflare/cloudflared:latest
    command: tunnel --no-autoupdate run
    networks:
      - public
    secrets:
      - tunnelKey
    environment:
      - TUNNEL_TOKEN=/run/secrets/tunnelKey
    deploy:
      replicas: 2
  pipeline:
    image: ghcr.io/redcloud442/pipeline:prod
     volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      mode: replicated
      replicas: 1
      update_config:
        order: start-first
    ports:
      - "8000:8000"
networks:
  public:
    external: true
