name: Docker Image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    environment: Production

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image for prod
        run: |
          docker build \
            --build-arg NEXT_PUBLIC_SUPABASE_URL="${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}" \
            --build-arg NEXT_PUBLIC_SUPABASE_ANON_KEY="${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}" \
            --build-arg NEXT_PUBLIC_BASE_URL="${{ secrets.NEXT_PUBLIC_BASE_URL }}" \
            --build-arg NEXT_PUBLIC_HCAPTCHA_SITE_KEY="${{ secrets.NEXT_PUBLIC_HCAPTCHA_SITE_KEY }}" \
            -t ghcr.io/redcloud442/pr1me:prod .

      - name: Verify Docker login
        run: docker info

      - name: Verify image tagging
        run: docker images

      - name: Push Docker image
        run: |
          docker push ghcr.io/redcloud442/starter:prod

      - name: Invoke Web Hook
        run: |
          curl -X POST -H "Content-Type: application/json" "Authorization: Bearer ${{ secrets.WEBHOOK_TOKEN }}" -d '{"message": "Docker image pushed"}' ${{ secrets.WEBHOOK_URL_CLIENT }}
