name: Docker Image CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Log in to GitHub Container Registry
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build and push Docker image
      - name: Build and push Docker image
        run: |
          IMAGE_TAG=ghcr.io/redcloud442/red:v${{ github.run_number }}
          docker build . --file Dockerfile --tag $IMAGE_TAG --tag ghcr.io/redcloud442/red:latest --no-cache
          docker push $IMAGE_TAG
          docker push ghcr.io/redcloud442/red:latest

      # Add SSH private key
      - name: Add SSH private key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      # Add server to known hosts
      - name: Add server to known hosts
        run: |
          ssh-keyscan -H pinkful.website >> ~/.ssh/known_hosts

      # Deploy to Docker Swarm
      - name: Deploy to Docker Swarm
        run: |
          ssh -o StrictHostKeyChecking=no adminuser@pinkful.website << EOF
          docker pull ghcr.io/redcloud442/red:v${{ github.run_number }}
          docker stack deploy --with-registry-auth --resolve-image always -c docker-stack.yml red-stack
          EOF
