name: Docker Image CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Log in to GitHub Container Registry
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build and push versioned Docker image
      - name: Build and push Docker image
        run: |
          IMAGE_TAG=ghcr.io/redcloud442/red:v${{ github.run_number }}
          docker build . --file Dockerfile --tag $IMAGE_TAG --no-cache
          docker push $IMAGE_TAG

      # Verify Docker login success
      - name: Verify Docker login
        run: docker info

      # Verify image tagging
      - name: Verify image tagging
        run: docker images

      # Deploy to Docker Swarm
      - name: Deploy to Docker Swarm
        run: |
          ssh adminuser@pinkful.website << EOF
          docker pull ghcr.io/redcloud442/red:v${{ github.run_number }}
          sed -i "s|image: ghcr.io/redcloud442/red:.*|image: ghcr.io/redcloud442/red:v${{ github.run_number }}|g" docker-stack.yml
          docker stack deploy --with-registry-auth -c docker-stack.yaml red-stack
          EOF
